site_name: 不动知海
site_url: https://mydomain.org/

theme:
  name: material
  language: zh

  include_search_page: false
  search_index_only: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - search

copyright: Copyright &copy; 2023 - 2024 by Sutang
